#Minecraft server properties
server-port=25565
motd=\u00A7aMy SMP \u00A77| Survival
online-mode=true
max-players=20
difficulty=normal
gamemode=survival
hardcore=false
pvp=true
spawn-protection=0
allow-flight=false
view-distance=10
simulation-distance=10
level-name=world
level-type=minecraft\:normal
generate-structures=true
spawn-animals=true
spawn-monsters=true
spawn-npcs=true
allow-nether=true
enable-command-block=true
white-list=false
enforce-whitelist=false
op-permission-level=4
network-compression-threshold=256
max-tick-time=60000
